testapp/urls.py
from django.urls import path
from . import views

app_name = "testapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('abouts/', views.abouts, name='abouts'),
    path('abouts/<int:about_id>/', views.about, name='about'),
    path('new_test/', views.new_test, name="new_test")
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls'))
]

testapp/models.py
from django.db import models

# Create your models here.
class Test(models.Model):
    """A test Table"""
    name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    comment = models.TextField(max_length=250)

    def __str__(self):
        return self.name

class New(models.Model):
    """Another test table"""
    author = models.ForeignKey(Test, on_delete=models.CASCADE)
    time_added = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=30)
    body = models.TextField(max_length=500, null=True)


    def __str__(self):
        return self.title

class Relative(models.Model):
    cousin = models.ManyToManyField(Test)
    meeting = models.CharField(max_length=20, null=True)
    details = models.TextField(max_length=500, null=True)

    def __str__(self):
        return self.meeting

class Remark(models.Model):
    subject = models.CharField(max_length=100, null=True)
    name = models.ForeignKey(Test, on_delete=models.CASCADE)
    content = models.TextField(max_length=250)

    def __str__(self):
        return self.subject

testapp/forms.py
from django import forms

from .models import Test


class TestForm(forms.ModelForm):

    class Meta:
        model = Test
        fields = ['name', 'age', 'comment']
        labels = {'name': ''}

testapp/views.py
from django.shortcuts import redirect, render
from .models import Test
from .forms import TestForm

# Create your views here.

def abouts(request):
    abouts = Test.objects.all()
    context = {'abouts':abouts}
    return render(request, 'testapp/abouts.html', context)

def index(request):
    return render(request, 'testapp/base.html')



def about(request, about_id):
    about = Test.objects.get(id=about_id)
    news = about.new_set.order_by('-time_added')
    context = {"about":about, "news": news}

    return render(request, 'testapp/about.html', context)

def new_test(request):
    if request.method != 'POST':
        form = TestForm()
    else:
        form = TestForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('testapp:abouts')
    context = {'form': form}
    
    return render(request, 'testapp/new_test.html', context)

testapp/templates/testapp/about.html
{% extends 'testapp/base.html' %}
{% block title %}
<title>About Us</title>
{% endblock %}

{% block content %}

<p>{{ about }}</p>
 {% for new in news%}
<ul>
   <li>
      <p>{{ new.time_added }}</p>
      <p>{{ new.title }}</p>
      <p>{{ new.body }}</p>
   </li>
</ul>
 {% endfor %}
{% endblock %}

testapp/templates/testapp/abouts.html
{% extends 'testapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>From Back</title>
    {%endblock%}
</head>
<body>
    {% block content %}
    <ul>
      {% for about in abouts %}
      <li>
          <a href="{% url 'testapp:about' about.id %}">{{ about }}</a>
      </li>
      {% endfor %}
    </ul>
    <a href="{% url 'testapp:new_test' %}">Add a new topic</a>
    {% endblock %}

    
</body>
</html>

testapp/templates/testapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'testapp/style.css' %}">
    {% block title %}
    <title>From Back</title>
    {%endblock%}
</head>
<body>
    <div class="links">
        <a href="{% url 'testapp:index' %}">Home</a>
        <a href="{% url 'testapp:abouts' %}">Abouts</a>
    </div>

    
    {% block content %}
    <div class="content">
        <h1>Welcome to my django Project</h1>
    </div>
    {% endblock %}

    


</body>
</html>

testapp/templates/testapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>From Back</title>
    {%endblock%}
</head>
<body>
    {% block content %}
        {% for test in tests %}
            <p>{{test}}</p>
        {% endfor %}
    {% endblock %}


</body>
</html>

testapp/templates/testapp/new_test.html
{% extends 'testapp/base.html' %}
{% block content %}
<p>Add a new Test</p>
<form action="{% url 'testapp:new_test' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add</button>   
</form>

{% endblock content %}